### ISSUE TITLE
Installing requirements fails on my MacOS 10.14

### ISSUE THREAD

**Issue by webhype** [cleanunicorn/theo#20]
`$ sudo pip install -r requirements.txt`

Fails with the following error:
```
  Preparing metadata (setup.py) ... done
Collecting zope.interface==4.6.0
  Downloading zope.interface-4.6.0.tar.gz (150 kB)
     |████████████████████████████████| 150 kB 233 kB/s            
  Preparing metadata (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /Users/macuser/dev/theo/venv/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/tmp/pip-install-43w_lkkk/zope-interface_aa293e8505b34d1a9a24e168adec7b63/setup.py'"'"'; __file__='"'"'/private/tmp/pip-install-43w_lkkk/zope-interface_aa293e8505b34d1a9a24e168adec7b63/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/tmp/pip-pip-egg-info-nurcrki2
       cwd: /private/tmp/pip-install-43w_lkkk/zope-interface_aa293e8505b34d1a9a24e168adec7b63/
  Complete output (5 lines):
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/tmp/pip-install-43w_lkkk/zope-interface_aa293e8505b34d1a9a24e168adec7b63/setup.py", line 26, in <module>
      from setuptools import setup, Extension, Feature
  ImportError: cannot import name 'Feature' from 'setuptools' (/Users/macuser/dev/theo/venv/lib/python3.9/site-packages/setuptools/__init__.py)
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/4e/d0/c9d16bd5b38de44a20c6dc5d5ed80a49626fafcb3db9f9efdc2a19026db6/zope.interface-4.6.0.tar.gz#sha256=1b3d0dcabc7c90b470e59e38a9acaa361be43b3a6ea644c0063951964717f0e5 (from https://pypi.org/simple/zope-interface/) (requires-python:>=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement zope.interface==4.6.0 (from versions: 3.3.0b1, 3.3.0b2, 3.3.0, 3.3.0.1, 3.4.0b1, 3.4.0, 3.4.1, 3.5.0, 3.5.1, 3.5.2, 3.5.3, 3.6.0, 3.6.1, 3.6.2, 3.6.3, 3.6.4, 3.6.5, 3.6.6, 3.6.7, 3.6.8, 3.7.0, 3.8.0, 4.0.0, 4.0.1, 4.0.2, 4.0.3, 4.0.4, 4.0.5, 4.1.0, 4.1.1, 4.1.2, 4.1.3, 4.2.0, 4.3.0, 4.3.1, 4.3.2, 4.3.3, 4.4.0, 4.4.1, 4.4.2, 4.4.3, 4.5.0, 4.6.0, 4.7.0, 4.7.1, 4.7.2, 5.0.0, 5.0.1, 5.0.2, 5.1.0, 5.1.1, 5.1.2, 5.2.0, 5.3.0a1, 5.3.0, 5.4.0)
ERROR: No matching distribution found for zope.interface==4.6.0
```
Ideas?

**Comment by 0xb00siff** [comment]
I switched to a different version of setuptools and it fixed this problem but then i started getting different errors
    error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> typed-ast
