### ISSUE TITLE
not installing properly on linux

### ISSUE THREAD

**Issue by 0xb00siff** [cleanunicorn/theo#21]
× python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-svt00zhe/zope-interface_c5e58486c9a9463b87d29fb577ab4813/setup.py", line 26, in <module>
          from setuptools import setup, Extension, Feature
      ImportError: cannot import name 'Feature' from 'setuptools' (/home/boosiff/.local/lib/python3.9/site-packages/setuptools/__init__.py)
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

any suggestions for me on the user side?

**Comment by 0xb00siff** [comment]
I fixed got past the feature and setuptools error but now i am getting different errors with such as failed building wheel for certain things a exiting with subprocess 1

**Comment by cr4ck3d1t** [comment]
clone this repo, open requirements.txt, and change the versions of plyvel and cytoolz to the following:
plyvel==1.2.0
cytoolz==0.11.2

then continue the install process as detailed in the "install from source" instructions and you should be all set.

**Comment by shashankhacker730** [comment]
Even with plyvel==1.2.0, cytoolz==0.11.2 there were errors with plyvel and numpy build. So I used latest version (plyvel==1.4.0 & numpy==1.23.3). Theo working fine now.

**Comment by codergrade** [comment]
sing cached zope.interface-4.6.0.tar.gz (150 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-_iruivlh/zope-interface_db3ca22f01e34ea0a3f5d314d1cf9531/setup.py", line 26, in <module>
          from setuptools import setup, Extension, Feature
      ImportError: cannot import name 'Feature' from 'setuptools' (/usr/lib/python3/dist-packages/setuptools/__init__.py)
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by codergrade** [comment]
getting the above error, please provide any solutions for it

**Comment by Vinz-90** [comment]
change zope version and is sorted.
