### ISSUE TITLE
attention : error in ubuntu installation 

### ISSUE THREAD

**Issue by codergrade** [cleanunicorn/theo#29]
sing cached zope.interface-4.6.0.tar.gz (150 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-_iruivlh/zope-interface_db3ca22f01e34ea0a3f5d314d1cf9531/setup.py", line 26, in <module>
          from setuptools import setup, Extension, Feature
      ImportError: cannot import name 'Feature' from 'setuptools' (/usr/lib/python3/dist-packages/setuptools/__init__.py)
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

******please solve this error i have encountered during the installation

**Comment by DJilaniE-070** [comment]
Same here, pip install keeps failing. Hope this can be resolved soon.
